import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider, ClerkLoaded, ClerkLoading, SignedIn,SignedOut, RedirectToSignIn } from "@clerk/nextjs";
import Loader from "@/components/Loader";
import { redirect } from "next/navigation";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CollabX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><ClerkLoading>
        <Loader/>
      </ClerkLoading>
      <ClerkLoaded>
        
        {children}
        
      </ClerkLoaded>
        
      </body>
      </html>
    </ClerkProvider>
    
  );
}
